### ISSUE TITLE
add the feature of browsing pdf from system

### ISSUE THREAD

**Issue by Mudit-Jxin7** [Mudit-Jxin7/chatpdf#1]
When any user click the browse pdf button he/she should be able to add pdfs

**Comment by sadidshaikh** [comment]
Hi, I am interested to work on this, can you please, what you want to do with the selected pdf. I am a beginner to open source so  apologies for any silly questions.

**Comment by sadidshaikh** [comment]
@Mudit-Jxin7 let me know if my proposed changes work
